import os
import requests
import subprocess
import json
import uuid
from dotenv import load_dotenv

load_dotenv()

class GitHubAgent:
    def __init__(self):
        self.token = os.getenv("GITHUB_TOKEN")
        self.owner = os.getenv("REPO_OWNER")
        self.repo = os.getenv("REPO_NAME")
        self.base_url = f"https://api.github.com/repos/{self.owner}/{self.repo}"
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json"
        }

    def create_pr(self, findings):
        if not self.token:
            return {"error": "GITHUB_TOKEN not found"}

        branch_name = f"fix/shadowcode-{uuid.uuid4().hex[:8]}"
        
        try:
            # 1. Create a new branch
            subprocess.run(["git", "checkout", "-b", branch_name], check=True)
            
            # 2. Apply fixes (Simple string replacement for demo)
            for f in findings:
                file_path = f['file']
                # Search for the file in the workspace
                full_path = None
                for root, _, files in os.walk("."):
                    if file_path in files:
                        full_path = os.path.join(root, file_path)
                        break
                
                if full_path and 'ai_fix' in f:
                    with open(full_path, 'r') as file:
                        content = file.read()
                    
                    # Be careful with replacement, using line number if possible
                    lines = content.splitlines()
                    if f['line'] <= len(lines):
                        lines[f['line']-1] = f['ai_fix']
                        new_content = "\n".join(lines)
                        with open(full_path, 'w') as file:
                            file.write(new_content)

            # 3. Commit and push
            subprocess.run(["git", "add", "."], check=True)
            subprocess.run(["git", "commit", "-m", "🛡️ ShadowCode AI: Automated Security Fixes"], check=True)
            
            # Push using the token in the URL to avoid authentication prompts
            push_url = f"https://{self.token}@github.com/{self.owner}/{self.repo}.git"
            subprocess.run(["git", "push", push_url, branch_name], check=True)

            # 4. Create Pull Request
            pr_data = {
                "title": "🛡️ ShadowCode AI: Security Remediation",
                "body": self._generate_pr_body(findings),
                "head": branch_name,
                "base": "main" # Assuming main branch
            }
            
            response = requests.post(f"{self.base_url}/pulls", headers=self.headers, json=pr_data)
            
            # Back to main branch
            subprocess.run(["git", "checkout", "main"], check=True)
            
            if response.status_code == 201:
                return response.json()
            else:
                return {"error": f"Failed to create PR: {response.text}"}

        except Exception as e:
            # Cleanup: try to go back to main
            subprocess.run(["git", "checkout", "main"], check=True)
            return {"error": str(e)}

    def _generate_pr_body(self, findings):
        body = "## 🛡️ ShadowCode AI Security Fixes\n\nI've detected and automatically patched the following security issues:\n\n"
        for f in findings:
            body += f"### {f['type']} in `{f['file']}`\n"
            body += f"- **Risk:** {f.get('ai_risk', 'High risk vulnerability detected.')}\n"
            body += f"- **Remediation:** {f['remediation']}\n\n"
        body += "\n---\n*Generated by ShadowCode AI Auditor*"
        return body

if __name__ == "__main__":
    # Test
    agent = GitHubAgent()
    # print(agent.create_pr([]))
